# Generated by Django 3.2.8 on 2021-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creditorscontrolaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('number', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'creditorscontrolaccount',
                'verbose_name_plural': 'creditorscontrolaccount',
            },
        ),
    ]
