# Generated by Django 3.2.8 on 2021-12-23 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave',
            new_name='LeaveApplication',
        ),
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-created'], 'verbose_name': 'LeaveApplication', 'verbose_name_plural': 'LeaveApplication'},
        ),
    ]
