# Generated by Django 3.2.8 on 2022-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklybudget', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybudget',
            name='labour',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
