# Generated by Django 3.2.8 on 2021-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasesLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('suppliername', models.CharField(max_length=350)),
                ('materialparticulars', models.CharField(max_length=350)),
                ('invoicedate', models.DateField()),
                ('accountpayable', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'PurchasesLedger',
                'verbose_name_plural': 'PurchasesLedger',
            },
        ),
    ]
