# Generated by Django 3.2.8 on 2021-12-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Author'},
        ),
        migrations.AlterModelOptions(
            name='facebook',
            options={'verbose_name': 'Facebook', 'verbose_name_plural': 'Facebook'},
        ),
        migrations.AlterModelOptions(
            name='linkedin',
            options={'verbose_name': 'Linkedin', 'verbose_name_plural': 'Linkedin'},
        ),
        migrations.AlterModelOptions(
            name='twitter',
            options={'verbose_name': 'Twitter', 'verbose_name_plural': 'Twitter'},
        ),
        migrations.RemoveField(
            model_name='facebook',
            name='post',
        ),
        migrations.RemoveField(
            model_name='linkedin',
            name='post',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
