# Generated by Django 3.2.8 on 2022-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20211223_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('context', models.ImageField(upload_to='')),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('authors', models.ManyToManyField(to='marketing.Author')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
