# Generated by Django 3.2.8 on 2022-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorsreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionManualLabourbroking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('requirement', models.TextField()),
                ('expectedoutcome', models.CharField(max_length=255)),
                ('expectedcompletion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstructionManualSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('requirement', models.TextField()),
                ('expectedoutcome', models.CharField(max_length=255)),
                ('expectedcompletion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InstructionManualTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('requirement', models.TextField()),
                ('expectedoutcome', models.CharField(max_length=255)),
                ('expectedcompletion', models.DateTimeField()),
            ],
        ),
    ]
