# Generated by Django 3.2.8 on 2022-01-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=150)),
                ('guardsallocated', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contract', models.CharField(max_length=150)),
                ('supervisor', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Guards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('qualifications', models.CharField(max_length=150)),
                ('workexperience', models.IntegerField()),
                ('profilepicture', models.ImageField(upload_to='')),
                ('reference', models.CharField(max_length=250)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('performanceappraisal', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Guards',
                'verbose_name_plural': 'Guards',
            },
        ),
        migrations.CreateModel(
            name='GuardsNeeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('duedate', models.DateField()),
            ],
            options={
                'verbose_name': 'GuardsNeeded',
                'verbose_name_plural': 'GuardsNeeded',
            },
        ),
    ]
