# Generated by Django 3.2.8 on 2021-12-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('mounth', models.DateTimeField()),
                ('labourhours', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('materials', models.DecimalField(decimal_places=2, max_digits=9)),
                ('travel', models.DecimalField(decimal_places=2, max_digits=9)),
                ('other', models.DecimalField(decimal_places=2, max_digits=9)),
                ('notes', models.CharField(max_length=450)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=9)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=9)),
                ('undercover', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'AnnualBudget',
                'verbose_name_plural': 'AnnualBudget',
            },
        ),
    ]
