# Generated by Django 3.2.8 on 2021-12-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=500)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'SalesLedger',
                'verbose_name_plural': 'SalesLedger',
            },
        ),
    ]
