# Generated by Django 3.2.8 on 2022-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagsratesbyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('destinationcode', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('usdrate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rtgsrate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Bagratesbyo',
                'verbose_name_plural': 'Bagratesbyo',
            },
        ),
        migrations.CreateModel(
            name='Bagsrateshre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('destinationcode', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('usdrate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rtgsrate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Bagrateshre',
                'verbose_name_plural': 'Bagrateshre',
            },
        ),
        migrations.CreateModel(
            name='Bulkratesbyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('destinationcode', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('usdrateperton', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rtgsrateperton', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Bulkratesbyo',
                'verbose_name_plural': 'Bulkratesbyo',
            },
        ),
        migrations.CreateModel(
            name='Bulkrateshre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('destinationcode', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('usdrateperton', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rtgsrateperton', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Bulkrateshre',
                'verbose_name_plural': 'Bulkrateshre',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckreg', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('driversname', models.CharField(max_length=100)),
                ('costcentre', models.CharField(max_length=100)),
                ('destinationname', models.CharField(max_length=100)),
                ('orderid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('timeout', models.TimeField()),
                ('timein', models.TimeField()),
                ('openingkms', models.CharField(max_length=100)),
                ('closingkms', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('litres', models.CharField(max_length=100)),
                ('priceperlitre', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Routes',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
