# Generated by Django 3.2.8 on 2022-01-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20220111_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancillaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Ancillaries',
                'verbose_name_plural': 'Ancillaries',
            },
        ),
        migrations.CreateModel(
            name='Fixedcost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=150)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Fixedcost',
                'verbose_name_plural': 'Fixedcost',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('origincountry', models.CharField(max_length=100)),
                ('destinationname', models.CharField(max_length=100)),
                ('destinationcountry', models.CharField(max_length=100)),
                ('origincode', models.CharField(max_length=100)),
                ('tripcode', models.CharField(max_length=100)),
                ('ppcso', models.CharField(max_length=100)),
                ('deliverynote', models.IntegerField()),
                ('shippingdate', models.TimeField()),
                ('planneddeliverydate', models.TimeField()),
                ('planneddeliveryday', models.TimeField()),
                ('currency', models.CharField(max_length=100)),
                ('shipping', models.DateField()),
                ('planneddelivery', models.DateField()),
                ('planneddistance', models.CharField(max_length=100)),
                ('realproductclass', models.CharField(max_length=100)),
                ('cpk', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vatpercentage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('variablecost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fixedcost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vatamount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Routes',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Variablekmcost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Variablekmcost',
                'verbose_name_plural': 'Variablekmcost',
            },
        ),
        migrations.RenameModel(
            old_name='Bagsrateshre',
            new_name='Bagsbyo',
        ),
        migrations.RenameModel(
            old_name='Bulkratesbyo',
            new_name='Bagshre',
        ),
        migrations.RenameModel(
            old_name='Bagsratesbyo',
            new_name='Bulkbyo',
        ),
        migrations.RenameModel(
            old_name='Bulkrateshre',
            new_name='Bulkhre',
        ),
        migrations.AlterModelOptions(
            name='bagsbyo',
            options={'verbose_name': 'Bagsbyo', 'verbose_name_plural': 'Bagsbyo'},
        ),
        migrations.AlterModelOptions(
            name='bagshre',
            options={'verbose_name': 'Bagshre', 'verbose_name_plural': 'Bagshre'},
        ),
        migrations.AlterModelOptions(
            name='bulkbyo',
            options={'verbose_name': 'Bulkbyo', 'verbose_name_plural': 'Bulkbyo'},
        ),
        migrations.AlterModelOptions(
            name='bulkhre',
            options={'verbose_name': 'Bulkhre', 'verbose_name_plural': 'Bulkhre'},
        ),
        migrations.RenameField(
            model_name='bagshre',
            old_name='rtgsrateperton',
            new_name='rtgsrate',
        ),
        migrations.RenameField(
            model_name='bagshre',
            old_name='usdrateperton',
            new_name='usdrate',
        ),
        migrations.RenameField(
            model_name='bulkbyo',
            old_name='rtgsrate',
            new_name='rtgsrateperton',
        ),
        migrations.RenameField(
            model_name='bulkbyo',
            old_name='usdrate',
            new_name='usdrateperton',
        ),
    ]
