# Generated by Django 3.2.8 on 2022-01-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_trip_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('qualifications', models.CharField(max_length=150)),
                ('workexperience', models.IntegerField()),
                ('profilepicture', models.ImageField(upload_to='')),
                ('reference', models.CharField(max_length=250)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('performanceappraisal', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='InternMechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('profilepicture', models.ImageField(upload_to='')),
                ('reference', models.CharField(max_length=250)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('performanceappraisal', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'InternMechanics',
                'verbose_name_plural': 'InternMechanics',
            },
        ),
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('qualifications', models.CharField(max_length=150)),
                ('workexperience', models.IntegerField()),
                ('profilepicture', models.ImageField(upload_to='')),
                ('reference', models.CharField(max_length=250)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('performanceappraisal', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
